### ISSUE TITLE
Lesson 2 - why is solution not correct?

### ISSUE THREAD

**Issue by dmitriz** [workshopper/stream-adventure#138]
I have `program.js`:

```
var fs = require('fs');
fs.createReadStream(process.argv[2]).pipe(process.stdout);
```

This seems to do what is asked, yet I get the error:

```
stream-adventure verify

TAP version 13
# (anonymous)
not ok 1 stream-adventure verify YOURFILE.js
  ---
    operator: equal
    expected: 1
    actual:   0
    at: Test.<anonymous> (/usr/local/lib/node_modules/stream-adventure/node_modules/adventure-verify/index.js:48:40)
module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/dmitrizaitsev/Dropbox/p/WebDev/Sandbox/stream-adventure/undefined'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
  ...
not ok 2 should be equivalent
  ---
    operator: deepEqual
    expected:
      'The Swarm\nExxilon\nVoord\nZanak humanoid\nTime Beetle\nBiomechanoid\nTractator\nShansheeth\nKraal\nDark Hoarde\n'
    actual:
      ''
    at: ConcatStream.<anonymous> (/usr/local/lib/node_modules/stream-adventure/node_modules/concat-stream/index.js:36:43)
  ...
not ok 3 successful exit code
  ---
    operator: equal
    expected: 0
    actual:   1
    at: ChildProcess.<anonymous> (/usr/local/lib/node_modules/stream-adventure/problems/meet_pipe/index.js:35:11)
  ...

1..3
# tests 3
# pass  0
# fail  3

#########################################
###   YOUR SOLUTION IS NOT CORRECT!   ###
#########################################
```

Any explanation?

**Comment by howheels** [comment]
The explanation is in the first error line:

> not ok 1 stream-adventure verify YOURFILE.js

You did not provide YOURFILE.js in your command line execution, therefore there is nothing to verify.

**Comment by Ntangen** [comment]
Yep - basically what @howheels said. You need to enter "stream-adventure verify program.js" on the command line. Your code is good to go.

**Comment by probil** [comment]
The same issue even though I pass a file as an argument.

Code:
```js
var fs = require('fs'),
    path = process.argv[2];

fs.createReadStream(path).pipe(process.stdout);
```

Run with:
```bash
stream-adventure verify program.js
```

Result is:
```
TAP version 13
# (anonymous)
fs.js:491
  binding.open(pathModule._makeLong(path),
          ^
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.open (fs.js:491:11)
    at ReadStream.open (fs.js:1613:6)
    at new ReadStream (fs.js:1600:10)
    at Object.fs.createReadStream (fs.js:1554:10)
    at Object.<anonymous> (/media/multimedia/Code/js/node_stream-adventure/MEET_PIPE/program.js:4:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
ok 1 stream-adventure verify YOURFILE.js
not ok 2 should be equal
  ---
    operator: equal
    expected: 'beep boop\n'
    actual:   ''
    at: ConcatStream.<anonymous> (/usr/lib/node_modules/stream-adventure/node_modules/concat-stream/index.js:36:43)
  ...
not ok 3 successful exit code
  ---
    operator: equal
    expected: 0
    actual:   1
    at: ChildProcess.<anonymous> (/usr/lib/node_modules/stream-adventure/problems/beep_boop/index.js:22:11)
  ...

1..3
# tests 3
# pass  1
# fail  2

#########################################
###   YOUR SOLUTION IS NOT CORRECT!   ###
#########################################

```

**Comment by ajaysubramanya26** [comment]
@probil : Try running the command 'stream-adventure' before you run 'stream-adventure verify program.js' . I had this issue while working with learnyounode .

**Comment by probil** [comment]
@ajaysubramanya26 Ok, thanks. I will try it.

**Comment by probil** [comment]
@ajaysubramanya26, works! Thanks for advice.
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@     YOUR SOLUTION IS CORRECT!     @@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

**Comment by ajaysubramanya26** [comment]
@probil : No Problem , happy learning.

**Comment by kalinchernev** [comment]
Closing as last comment from @probil is positive :)
