### ISSUE TITLE
DeprecationWarning: Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by mpalmr** [workshopper/stream-adventure#200]
Was first trying to use this and when running the first adventure _Beep Boop_ this was printed to my console:

```
(node:42039) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Just to make sure everything is working, just write a `program.js` that outputs
the string "beep boop" with a `console.log()`.

To verify your `program.js` against the expected output, do:

  stream-adventure verify program.js

for more options, run `stream-adventure help`.

mpalmer:streams:%
```

It was a little confusing figuring out the instructions was directly below the deprecation warning and mistook it the whole program failing. Things appear to work fine but I can foresee this confusing a lot of people.

Behaviour was consistent on Node v7.15.0 and v4.x.

### Edit

I keep getting this as I go along:

```
mpalmer:streams:% stream-adventure verify program.js                                                                                                                                             <master ✗>

TAP version 13
# (anonymous)
ok 1 stream-adventure verify YOURFILE.js
ok 2 should be equal
ok 3 successful exit code

1..3
# tests 3
# pass  3

# ok


@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@     YOUR SOLUTION IS CORRECT!     @@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@



(node:43710) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
// Here's the reference solution:

  console.log('beep boop');

mpalmer:streams:%
```

**Comment by antosan** [comment]
Actually, this warning is not there on Node v4.x.

The warning comes from [`adventure`](https://github.com/workshopper/adventure) which [`stream-adventure`](https://github.com/workshopper/stream-adventure) uses and this [PR](https://github.com/workshopper/adventure/pull/11) on `adventure` should fix the issue.

**Comment by benschac** [comment]
This bug is still there. Can someone merge that PR?

**Comment by albanirneves** [comment]
![screenshot_20180317171545](https://user-images.githubusercontent.com/16230017/37559551-f538c7c2-2a06-11e8-8304-767d1845082d.png)
Same here..
v8.3.0

**Comment by gdelfino** [comment]
I am also getting this deprecation message.

    (node:11652) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

I am using node v8.9.4 under Windows 7.

**Comment by theangellmethod** [comment]
I get this on node v8.11.1 with Win10.

**Comment by prochafilho** [comment]
I also get this warning on node v9.11.1 on OSX

**Comment by ajelston** [comment]
This is now a fatal error on v10.2.1 - I'm unable to run any of the lessons in stream-adventure. 

Relevant lines from backtrace:

at Object.fs.writeFile (fs.js:1276:14)
    at Shop.save (/home/me/.nvm/versions/node/v10.2.1/lib/node_modules/stream-adventure/node_modules/adventure/index.js:288:8)
    at Shop.select (/home/me/.nvm/versions/node/v10.2.1/lib/node_modules/stream-adventure/node_modules/adventure/index.js:246:10)

**Comment by ccarruitero** [comment]
The PR mentioned in https://github.com/workshopper/stream-adventure/issues/200#issuecomment-280884606 was merged some time ago, so closing this.
