### ISSUE TITLE
Node Version: 10.7.0 not supported

### ISSUE THREAD

**Issue by hadnazzar** [workshopper/stream-adventure#213]
Hello when i try to run with node 10.7.0 i get error. 

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: shutdown ENOTCONN
    at ReadStream.Socket._final (net.js:369:25)
    at callFinal (_stream_writable.js:612:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```

**Comment by Angristan** [comment]
Version 10.0.0 is not affected. 10.1.0 to 10.7.0 are affected

**Comment by MikkeMF** [comment]
Also Node Version 10.9.0 is affected with this issue. Any updates or workarounds on this?
<img width="573" alt="screen shot 2018-09-03 at 3 01 35 pm" src="https://user-images.githubusercontent.com/33631149/45002319-5e76ed00-af8a-11e8-8af3-88585bf9b7a1.png">

**Comment by Tesser4** [comment]
Same with node v10.10.0.
But in my case the error is '**shutdown EPIPE**' instead of '**shutdown ENOTCONN**'.

```
events.js:167
    throw er; // Unhandled 'error' event
    ^

Error: shutdown EPIPE
    at ReadStream.Socket._final (net.js:370:25)
    at callFinal (_stream_writable.js:612:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by Tesser4** [comment]
Yeap, your solution @cristianberroeta just worked for me also, with Node v10.10.0.

**Comment by cristianberroeta** [comment]
I've just created the pull request in the [adventure repository](https://github.com/workshopper/adventure).

To clarify, once it is approved, we will have to create a pull request to update that 'adventure' module version number we depend on.
