### ISSUE TITLE
Throw in event

### ISSUE THREAD

**Issue by huanghe2015** [workshopper/stream-adventure#219]
STREAM ADVENTURE                                                   
    ----------------                                                   
   ☞ BEEP BOOP                                                          
    MEET PIPE                                                          
    INPUT OUTPUT                                                       
    TRANSFORM                                                          
    LINES                                                              
    CONCAT                                                             
    HTTP SERVER                                                        
    HTTP CLIENT                                                        
    WEBSOCKETS                                                         
    HTML STREAM                                                        
    DUPLEXER                                                           
    DUPLEXER REDUX                                                     
    COMBINER                                                           
    CRYPT                                                              
    SECRETZ                                                            
    -----------------                                                  
                                                                       
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: shutdown EPIPE
    at ReadStream.Socket._final (net.js:364:25)
    at callFinal (_stream_writable.js:612:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by pugdogs** [comment]
[seems to be the same issue](https://github.com/workshopper/stream-adventure/issues/213#issue-342450147)

**Comment by huanghe2015** [comment]
Yes,duplicated.Thanks. @pugdogs
