### ISSUE TITLE
combiner challenge - ERR_STREAM_CANNOT_PIPE (not readable)

### ISSUE THREAD

**Issue by univ1** [workshopper/stream-adventure#265]
I'm not really sure what's causing this, my combine function looks like this:  

return combine(myWritable, split2(), t2Stream, gzip, myReadable); where t2Stream is the through2 stream that I use to modify a booksByGenres object. It has a transformFunction "write", and a flushFunction "end". Much like in the previous duplexer-redux challenge, I don't use this.push() inside "write" to directly modify the contents of the stream, instead I use the t2stream exclusively to modify the booksInGenres object. Anyway, here is the error code.

events.js:353
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_CANNOT_PIPE]: Cannot pipe, not readable
    at MyWritable.Writable.pipe (internal/streams/writable.js:255:24)
    at recurse (C:\Users\Absolute\learn\nodeschool\node_modules\stream-combiner\index.js:27:16)
    at module.exports (C:\Users\Absolute\learn\nodeschool\node_modules\stream-combiner\index.js:31:3)
    at Exercise.module.exports [as submissionFn] (C:\Users\Absolute\learn\nodeschool\stream-adventure\combiner.js:39:9)
    at Exercise.<anonymous> (C:\Users\Absolute\AppData\Roaming\npm\node_modules\stream-adventure\lib\exportFnExercise.js:29:33)
    at next (C:\Users\Absolute\AppData\Roaming\npm\node_modules\stream-adventure\node_modules\workshopper-exercise\exercise.js:170:19)
    at Exercise.process (C:\Users\Absolute\AppData\Roaming\npm\node_modules\stream-adventure\node_modules\workshopper-exercise\exercise.js:177:5)
    at Exercise.<anonymous> (C:\Users\Absolute\AppData\Roaming\npm\node_modules\stream-adventure\node_modules\workshopper-exercise\exercise.js:147:10)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
Emitted 'error' event on Stream instance at:
    at MyWritable.reemit (C:\Users\Absolute\learn\nodeschool\node_modules\duplexer\index.js:85:16)
    at MyWritable.emit (events.js:376:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ERR_STREAM_CANNOT_PIPE'
}

**Comment by univ1** [comment]
I figured it out. Although it's unclear based on the text, you aren't supposed to supply the writable and readable streams manually, those will be supplied internally. A correct combine function looks like this: combine(split2(), t2Stream, gzip);
